[context.production]
  environment = { DB_HOST = "https://alexandria-reader.herokuapp.com" }
  command = "echo 'production' && echo $DB_HOST"

[context.deploy-preview]
  environment = { DB_HOST = "https://alexandria-reader-staging.herokuapp.com" }
  command = "echo 'preview' && echo $DB_HOST"

[context.branch-deploy]
  environment = { DB_HOST = "https://alexandria-reader-staging.herokuapp.com" }
  command = "echo 'branch' && echo $DB_HOST"
